version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai
    environment:
      POSTGRES_USER: finace-ai
      POSTGRES_PASSWORD: finace-ai
      POSTGRES_DB: finace-ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
 